services:
  injection-lab:
    build:
      context: ./docker
    container_name: injection-lab
    ports:
      - "8080:8080"
    volumes:
      - ./src:/home/student/lab/src
      - ./docs:/home/student/lab/docs
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    privileged: true
    restart: unless-stopped
