[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x800x24
autorestart=true
user=student

[program:xfce4]
command=/usr/bin/startxfce4
environment=DISPLAY=":1"
autorestart=true
user=student

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -nopw -listen localhost -xkb -ncache 10 -ncache_cr -forever
autorestart=true
user=student

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ 8080 localhost:5900
autorestart=true
user=student
